<?php

declare(strict_types=1);

namespace ConorSmith\PokemonTest\Gameplay\App\UseCases;

use ConorSmith\Pokemon\Gameplay\App\UseCases\LevelUpPokemon;
use ConorSmith\Pokemon\SharedKernel\Domain\GymBadge;
use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\Attributes\Test;
use PHPUnit\Framework\TestCase;
use function PHPUnit\Framework\assertThat;
use function PHPUnit\Framework\identicalTo;

final class LevelUpPokemonTest extends TestCase
{
    #[Test]
    #[DataProvider('providerOfUseCases')]
    function is_does_something(int $levelLimit, int $currentLevel, int $newLevel)
    {
        assertThat(
            LevelUpPokemon::calculateNewLevel($currentLevel, $levelLimit),
            identicalTo($newLevel),
        );
    }

    public static function providerOfUseCases(): array
    {
        return [
            [GymBadge::BOULDER->levelLimit(), 0, 0 + 1],

            [GymBadge::CASCADE->levelLimit(), 0, 0 + 1],

            [GymBadge::THUNDER->levelLimit(), 0, 0 + 1],

            [GymBadge::RAINBOW->levelLimit(), 0, 0 + 2],
            [GymBadge::RAINBOW->levelLimit(), 10, 10 + 2],
            [GymBadge::RAINBOW->levelLimit(), 19, 20],
            [GymBadge::RAINBOW->levelLimit(), 20, 20 + 1],

            [GymBadge::SOUL->levelLimit(), 0, 0 + 2],
            [GymBadge::SOUL->levelLimit(), 10, 10 + 2],
            [GymBadge::SOUL->levelLimit(), 19, 20],
            [GymBadge::SOUL->levelLimit(), 20, 20 + 1],

            [GymBadge::MARSH->levelLimit(), 0, 0 + 10],
            [GymBadge::MARSH->levelLimit(), 10, 10 + 10],
            [GymBadge::MARSH->levelLimit(), 15, 20],
            [GymBadge::MARSH->levelLimit(), 20, 20 + 2],
            [GymBadge::MARSH->levelLimit(), 29, 30],
            [GymBadge::MARSH->levelLimit(), 30, 30 + 1],

            [GymBadge::VOLCANO->levelLimit(), 0, 0 + 10],
            [GymBadge::VOLCANO->levelLimit(), 10, 10 + 10],
            [GymBadge::VOLCANO->levelLimit(), 15, 20],
            [GymBadge::VOLCANO->levelLimit(), 20, 20 + 2],
            [GymBadge::VOLCANO->levelLimit(), 29, 30],
            [GymBadge::VOLCANO->levelLimit(), 30, 30 + 1],

            [GymBadge::EARTH->levelLimit(), 0, 20],
            [GymBadge::EARTH->levelLimit(), 10, 20],
            [GymBadge::EARTH->levelLimit(), 20, 20 + 10],
            [GymBadge::EARTH->levelLimit(), 25, 30],
            [GymBadge::EARTH->levelLimit(), 30, 30 + 2],
            [GymBadge::EARTH->levelLimit(), 40, 40 + 2],
            [GymBadge::EARTH->levelLimit(), 49, 50],
            [GymBadge::EARTH->levelLimit(), 50, 50 + 1],

            [GymBadge::ZEPHYR->levelLimit(), 0, 20],
            [GymBadge::ZEPHYR->levelLimit(), 10, 20],
            [GymBadge::ZEPHYR->levelLimit(), 20, 20 + 10],
            [GymBadge::ZEPHYR->levelLimit(), 25, 30],
            [GymBadge::ZEPHYR->levelLimit(), 30, 30 + 2],
            [GymBadge::ZEPHYR->levelLimit(), 40, 40 + 2],
            [GymBadge::ZEPHYR->levelLimit(), 49, 50],
            [GymBadge::ZEPHYR->levelLimit(), 50, 50 + 1],

            [GymBadge::HIVE->levelLimit(), 0, 20],
            [GymBadge::HIVE->levelLimit(), 10, 20],
            [GymBadge::HIVE->levelLimit(), 20, 20 + 10],
            [GymBadge::HIVE->levelLimit(), 25, 30],
            [GymBadge::HIVE->levelLimit(), 30, 30 + 2],
            [GymBadge::HIVE->levelLimit(), 40, 40 + 2],
            [GymBadge::HIVE->levelLimit(), 49, 50],
            [GymBadge::HIVE->levelLimit(), 50, 50 + 1],

            [GymBadge::PLAIN->levelLimit(), 0, 20],
            [GymBadge::PLAIN->levelLimit(), 10, 20],
            [GymBadge::PLAIN->levelLimit(), 20, 20 + 10],
            [GymBadge::PLAIN->levelLimit(), 25, 30],
            [GymBadge::PLAIN->levelLimit(), 30, 30 + 2],
            [GymBadge::PLAIN->levelLimit(), 40, 40 + 2],
            [GymBadge::PLAIN->levelLimit(), 49, 50],
            [GymBadge::PLAIN->levelLimit(), 50, 50 + 1],

            [GymBadge::FOG->levelLimit(), 0, 20],
            [GymBadge::FOG->levelLimit(), 10, 20],
            [GymBadge::FOG->levelLimit(), 20, 30],
            [GymBadge::FOG->levelLimit(), 30, 40],
            [GymBadge::FOG->levelLimit(), 40, 40 + 10],
            [GymBadge::FOG->levelLimit(), 45, 50],
            [GymBadge::FOG->levelLimit(), 50, 50 + 2],
            [GymBadge::FOG->levelLimit(), 60, 60 + 2],
            [GymBadge::FOG->levelLimit(), 69, 70],
            [GymBadge::FOG->levelLimit(), 70, 70 + 1],

            [GymBadge::STORM->levelLimit(), 0, 20],
            [GymBadge::STORM->levelLimit(), 10, 20],
            [GymBadge::STORM->levelLimit(), 20, 30],
            [GymBadge::STORM->levelLimit(), 30, 50],
            [GymBadge::STORM->levelLimit(), 40, 50],
            [GymBadge::STORM->levelLimit(), 50, 50 + 10],
            [GymBadge::STORM->levelLimit(), 60, 60 + 10],
            [GymBadge::STORM->levelLimit(), 65, 70],
            [GymBadge::STORM->levelLimit(), 70, 70 + 2],
            [GymBadge::STORM->levelLimit(), 80, 80 + 2],
            [GymBadge::STORM->levelLimit(), 89, 90],
            [GymBadge::STORM->levelLimit(), 90, 90 + 1],

            [GymBadge::MINERAL->levelLimit(), 0, 20],
            [GymBadge::MINERAL->levelLimit(), 10, 20],
            [GymBadge::MINERAL->levelLimit(), 20, 30],
            [GymBadge::MINERAL->levelLimit(), 30, 50],
            [GymBadge::MINERAL->levelLimit(), 40, 50],
            [GymBadge::MINERAL->levelLimit(), 50, 50 + 10],
            [GymBadge::MINERAL->levelLimit(), 60, 60 + 10],
            [GymBadge::MINERAL->levelLimit(), 65, 70],
            [GymBadge::MINERAL->levelLimit(), 70, 70 + 2],
            [GymBadge::MINERAL->levelLimit(), 80, 80 + 2],
            [GymBadge::MINERAL->levelLimit(), 89, 90],
            [GymBadge::MINERAL->levelLimit(), 90, 90 + 1],

            [GymBadge::GLACIER->levelLimit(), 0, 20],
            [GymBadge::GLACIER->levelLimit(), 10, 20],
            [GymBadge::GLACIER->levelLimit(), 20, 30],
            [GymBadge::GLACIER->levelLimit(), 30, 50],
            [GymBadge::GLACIER->levelLimit(), 40, 50],
            [GymBadge::GLACIER->levelLimit(), 50, 50 + 10],
            [GymBadge::GLACIER->levelLimit(), 60, 60 + 10],
            [GymBadge::GLACIER->levelLimit(), 65, 70],
            [GymBadge::GLACIER->levelLimit(), 70, 70 + 2],
            [GymBadge::GLACIER->levelLimit(), 80, 80 + 2],
            [GymBadge::GLACIER->levelLimit(), 89, 90],
            [GymBadge::GLACIER->levelLimit(), 90, 90 + 1],

            [GymBadge::RISING->levelLimit(), 0, 20],
            [GymBadge::RISING->levelLimit(), 10, 20],
            [GymBadge::RISING->levelLimit(), 20, 30],
            [GymBadge::RISING->levelLimit(), 30, 50],
            [GymBadge::RISING->levelLimit(), 40, 50],
            [GymBadge::RISING->levelLimit(), 50, 70],
            [GymBadge::RISING->levelLimit(), 60, 70],
            [GymBadge::RISING->levelLimit(), 70, 70 + 10],
            [GymBadge::RISING->levelLimit(), 80, 80 + 10],
            [GymBadge::RISING->levelLimit(), 85, 90],
            [GymBadge::RISING->levelLimit(), 90, 90 + 2],
            [GymBadge::RISING->levelLimit(), 99, 100],
            [GymBadge::RISING->levelLimit(), 100, 100 + 1],

            [GymBadge::STONE->levelLimit(), 0, 20],
            [GymBadge::STONE->levelLimit(), 10, 20],
            [GymBadge::STONE->levelLimit(), 20, 30],
            [GymBadge::STONE->levelLimit(), 30, 50],
            [GymBadge::STONE->levelLimit(), 40, 50],
            [GymBadge::STONE->levelLimit(), 50, 70],
            [GymBadge::STONE->levelLimit(), 60, 70],
            [GymBadge::STONE->levelLimit(), 70, 70 + 10],
            [GymBadge::STONE->levelLimit(), 80, 80 + 10],
            [GymBadge::STONE->levelLimit(), 85, 90],
            [GymBadge::STONE->levelLimit(), 90, 90 + 2],
            [GymBadge::STONE->levelLimit(), 99, 100],
            [GymBadge::STONE->levelLimit(), 100, 100 + 1],

            [GymBadge::KNUCKLE->levelLimit(), 0, 20],
            [GymBadge::KNUCKLE->levelLimit(), 10, 20],
            [GymBadge::KNUCKLE->levelLimit(), 20, 30],
            [GymBadge::KNUCKLE->levelLimit(), 30, 50],
            [GymBadge::KNUCKLE->levelLimit(), 40, 50],
            [GymBadge::KNUCKLE->levelLimit(), 50, 70],
            [GymBadge::KNUCKLE->levelLimit(), 60, 70],
            [GymBadge::KNUCKLE->levelLimit(), 70, 70 + 10],
            [GymBadge::KNUCKLE->levelLimit(), 80, 80 + 10],
            [GymBadge::KNUCKLE->levelLimit(), 85, 90],
            [GymBadge::KNUCKLE->levelLimit(), 90, 90 + 2],
            [GymBadge::KNUCKLE->levelLimit(), 99, 100],
            [GymBadge::KNUCKLE->levelLimit(), 100, 100 + 1],

            [GymBadge::DYNAMO->levelLimit(), 0, 20],
            [GymBadge::DYNAMO->levelLimit(), 10, 20],
            [GymBadge::DYNAMO->levelLimit(), 20, 30],
            [GymBadge::DYNAMO->levelLimit(), 30, 50],
            [GymBadge::DYNAMO->levelLimit(), 40, 50],
            [GymBadge::DYNAMO->levelLimit(), 50, 70],
            [GymBadge::DYNAMO->levelLimit(), 60, 70],
            [GymBadge::DYNAMO->levelLimit(), 70, 70 + 10],
            [GymBadge::DYNAMO->levelLimit(), 80, 80 + 10],
            [GymBadge::DYNAMO->levelLimit(), 85, 90],
            [GymBadge::DYNAMO->levelLimit(), 90, 90 + 2],
            [GymBadge::DYNAMO->levelLimit(), 99, 100],
            [GymBadge::DYNAMO->levelLimit(), 100, 100 + 1],

            [GymBadge::HEAT->levelLimit(), 0, 20],
            [GymBadge::HEAT->levelLimit(), 10, 20],
            [GymBadge::HEAT->levelLimit(), 20, 30],
            [GymBadge::HEAT->levelLimit(), 30, 50],
            [GymBadge::HEAT->levelLimit(), 40, 50],
            [GymBadge::HEAT->levelLimit(), 50, 70],
            [GymBadge::HEAT->levelLimit(), 60, 70],
            [GymBadge::HEAT->levelLimit(), 70, 90],
            [GymBadge::HEAT->levelLimit(), 80, 90],
            [GymBadge::HEAT->levelLimit(), 85, 90],
            [GymBadge::HEAT->levelLimit(), 90, 90 + 10],
            [GymBadge::HEAT->levelLimit(), 95, 100],
            [GymBadge::HEAT->levelLimit(), 100, 100 + 2],
            [GymBadge::HEAT->levelLimit(), 110, 110 + 2],
            [GymBadge::HEAT->levelLimit(), 119, 120],
            [GymBadge::HEAT->levelLimit(), 120, 120 + 1],

            [GymBadge::BALANCE->levelLimit(), 0, 20],
            [GymBadge::BALANCE->levelLimit(), 10, 20],
            [GymBadge::BALANCE->levelLimit(), 20, 30],
            [GymBadge::BALANCE->levelLimit(), 30, 50],
            [GymBadge::BALANCE->levelLimit(), 40, 50],
            [GymBadge::BALANCE->levelLimit(), 50, 70],
            [GymBadge::BALANCE->levelLimit(), 60, 70],
            [GymBadge::BALANCE->levelLimit(), 70, 90],
            [GymBadge::BALANCE->levelLimit(), 80, 90],
            [GymBadge::BALANCE->levelLimit(), 85, 90],
            [GymBadge::BALANCE->levelLimit(), 90, 100],
            [GymBadge::BALANCE->levelLimit(), 100, 100 + 10],
            [GymBadge::BALANCE->levelLimit(), 110, 110 + 10],
            [GymBadge::BALANCE->levelLimit(), 115, 120],
            [GymBadge::BALANCE->levelLimit(), 120, 120 + 2],
            [GymBadge::BALANCE->levelLimit(), 130, 130 + 2],
            [GymBadge::BALANCE->levelLimit(), 139, 140],
            [GymBadge::BALANCE->levelLimit(), 140, 140 + 1],

            [GymBadge::FEATHER->levelLimit(), 0, 20],
            [GymBadge::FEATHER->levelLimit(), 10, 20],
            [GymBadge::FEATHER->levelLimit(), 20, 30],
            [GymBadge::FEATHER->levelLimit(), 30, 50],
            [GymBadge::FEATHER->levelLimit(), 40, 50],
            [GymBadge::FEATHER->levelLimit(), 50, 70],
            [GymBadge::FEATHER->levelLimit(), 60, 70],
            [GymBadge::FEATHER->levelLimit(), 70, 90],
            [GymBadge::FEATHER->levelLimit(), 80, 90],
            [GymBadge::FEATHER->levelLimit(), 85, 90],
            [GymBadge::FEATHER->levelLimit(), 90, 100],
            [GymBadge::FEATHER->levelLimit(), 100, 120],
            [GymBadge::FEATHER->levelLimit(), 110, 120],
            [GymBadge::FEATHER->levelLimit(), 120, 120 + 10],
            [GymBadge::FEATHER->levelLimit(), 130, 130 + 10],
            [GymBadge::FEATHER->levelLimit(), 135, 140],
            [GymBadge::FEATHER->levelLimit(), 140, 140 + 2],
            [GymBadge::FEATHER->levelLimit(), 149, 150],
            [GymBadge::FEATHER->levelLimit(), 150, 150 + 1],

            [GymBadge::MIND->levelLimit(), 0, 20],
            [GymBadge::MIND->levelLimit(), 10, 20],
            [GymBadge::MIND->levelLimit(), 20, 30],
            [GymBadge::MIND->levelLimit(), 30, 50],
            [GymBadge::MIND->levelLimit(), 40, 50],
            [GymBadge::MIND->levelLimit(), 50, 70],
            [GymBadge::MIND->levelLimit(), 60, 70],
            [GymBadge::MIND->levelLimit(), 70, 90],
            [GymBadge::MIND->levelLimit(), 80, 90],
            [GymBadge::MIND->levelLimit(), 85, 90],
            [GymBadge::MIND->levelLimit(), 90, 100],
            [GymBadge::MIND->levelLimit(), 100, 120],
            [GymBadge::MIND->levelLimit(), 110, 120],
            [GymBadge::MIND->levelLimit(), 120, 140],
            [GymBadge::MIND->levelLimit(), 130, 140],
            [GymBadge::MIND->levelLimit(), 140, 140 + 10],
            [GymBadge::MIND->levelLimit(), 145, 150],
            [GymBadge::MIND->levelLimit(), 150, 150 + 2],
            [GymBadge::MIND->levelLimit(), 159, 160],
            [GymBadge::MIND->levelLimit(), 160, 160 + 1],

            [GymBadge::RAIN->levelLimit(), 0, 20],
            [GymBadge::RAIN->levelLimit(), 10, 20],
            [GymBadge::RAIN->levelLimit(), 20, 30],
            [GymBadge::RAIN->levelLimit(), 30, 50],
            [GymBadge::RAIN->levelLimit(), 40, 50],
            [GymBadge::RAIN->levelLimit(), 50, 70],
            [GymBadge::RAIN->levelLimit(), 60, 70],
            [GymBadge::RAIN->levelLimit(), 70, 90],
            [GymBadge::RAIN->levelLimit(), 80, 90],
            [GymBadge::RAIN->levelLimit(), 85, 90],
            [GymBadge::RAIN->levelLimit(), 90, 100],
            [GymBadge::RAIN->levelLimit(), 100, 120],
            [GymBadge::RAIN->levelLimit(), 110, 120],
            [GymBadge::RAIN->levelLimit(), 120, 140],
            [GymBadge::RAIN->levelLimit(), 130, 140],
            [GymBadge::RAIN->levelLimit(), 140, 150],
            [GymBadge::RAIN->levelLimit(), 150, 150 + 10],
            [GymBadge::RAIN->levelLimit(), 155, 160],
            [GymBadge::RAIN->levelLimit(), 160, 160 + 2],
            [GymBadge::RAIN->levelLimit(), 169, 170],
            [GymBadge::RAIN->levelLimit(), 170, 170 + 1],
        ];
    }
}
