<?php
declare(strict_types=1);

use ConorSmith\Pokemon\LocationId;

return [
    LocationId::ROUTE_26 => "https://archives.bulbagarden.net/media/upload/3/3a/Kanto_Route_26_Map.png",
    LocationId::ROUTE_27 => "https://archives.bulbagarden.net/media/upload/4/46/Kanto_Route_27_Map.png",
    LocationId::TOHJO_FALLS => "https://archives.bulbagarden.net/media/upload/7/77/Kanto_Tohjo_Falls_Map.png",
    LocationId::ROUTE_28 => "https://archives.bulbagarden.net/media/upload/5/5b/Kanto_Route_28_Map.png",
    LocationId::MT_SILVER_EXTERIOR => "https://archives.bulbagarden.net/media/upload/9/95/Johto_Mt_Silver_Map.png",
    LocationId::MT_SILVER_1F => "https://archives.bulbagarden.net/media/upload/9/95/Johto_Mt_Silver_Map.png",
    LocationId::MT_SILVER_2F => "https://archives.bulbagarden.net/media/upload/9/95/Johto_Mt_Silver_Map.png",
    LocationId::MT_SILVER_3F => "https://archives.bulbagarden.net/media/upload/9/95/Johto_Mt_Silver_Map.png",
    LocationId::MT_SILVER_LOWER_MOUNTAINSIDE => "https://archives.bulbagarden.net/media/upload/9/95/Johto_Mt_Silver_Map.png",
    LocationId::MT_SILVER_UPPER_MOUNTAINSIDE => "https://archives.bulbagarden.net/media/upload/9/95/Johto_Mt_Silver_Map.png",
    LocationId::MT_SILVER_SUMMIT => "https://archives.bulbagarden.net/media/upload/9/95/Johto_Mt_Silver_Map.png",
    LocationId::NEW_BARK_TOWN => "https://archives.bulbagarden.net/media/upload/3/39/Johto_New_Bark_Town_Map.png",
    LocationId::ROUTE_29 => "https://archives.bulbagarden.net/media/upload/f/f9/Johto_Route_29_Map.png",
    LocationId::CHERRYGROVE_CITY => "https://archives.bulbagarden.net/media/upload/2/23/Johto_Cherrygrove_City_Map.png",
    LocationId::ROUTE_30 => "https://archives.bulbagarden.net/media/upload/7/76/Johto_Route_30_Map.png",
    LocationId::ROUTE_31 => "https://archives.bulbagarden.net/media/upload/2/2b/Johto_Route_31_Map.png",
    LocationId::DARK_CAVE_WEST => "https://archives.bulbagarden.net/media/upload/4/47/Johto_Dark_Cave_Map.png",
    LocationId::DARK_CAVE_EAST => "https://archives.bulbagarden.net/media/upload/4/47/Johto_Dark_Cave_Map.png",
    LocationId::VIOLET_CITY => "https://archives.bulbagarden.net/media/upload/1/1f/Johto_Violet_City_Map.png",
    LocationId::VIOLET_GYM => "https://archives.bulbagarden.net/media/upload/1/1f/Johto_Violet_City_Map.png",
    LocationId::SPROUT_TOWER_1F => "https://archives.bulbagarden.net/media/upload/b/b8/Johto_Sprout_Tower_Map.png",
    LocationId::SPROUT_TOWER_2F => "https://archives.bulbagarden.net/media/upload/b/b8/Johto_Sprout_Tower_Map.png",
    LocationId::SPROUT_TOWER_3F => "https://archives.bulbagarden.net/media/upload/b/b8/Johto_Sprout_Tower_Map.png",
    LocationId::ROUTE_32 => "https://archives.bulbagarden.net/media/upload/c/ce/Johto_Route_32_Map.png",
    LocationId::RUINS_OF_ALPH_OUTSIDE => "https://archives.bulbagarden.net/media/upload/1/18/Johto_Ruins_of_Alph_Map.png",
    LocationId::RUINS_OF_ALPH_CHAMBER => "https://archives.bulbagarden.net/media/upload/1/18/Johto_Ruins_of_Alph_Map.png",
    LocationId::UNION_CAVE_1F => "https://archives.bulbagarden.net/media/upload/c/c9/Johto_Union_Cave_Map.png",
    LocationId::UNION_CAVE_B1F => "https://archives.bulbagarden.net/media/upload/c/c9/Johto_Union_Cave_Map.png",
    LocationId::UNION_CAVE_B2F => "https://archives.bulbagarden.net/media/upload/c/c9/Johto_Union_Cave_Map.png",
    LocationId::ROUTE_33 => "https://archives.bulbagarden.net/media/upload/b/b4/Johto_Route_33_Map.png",
    LocationId::AZALEA_TOWN => "https://archives.bulbagarden.net/media/upload/b/b4/Johto_Route_33_Map.png",
    LocationId::AZALEA_GYM => "https://archives.bulbagarden.net/media/upload/b/b4/Johto_Route_33_Map.png",
    LocationId::SLOWPOKE_WELL_ENTRANCE => "https://archives.bulbagarden.net/media/upload/5/5d/Johto_Slowpoke_Well_Map.png",
    LocationId::SLOWPOKE_WELL_B1F => "https://archives.bulbagarden.net/media/upload/5/5d/Johto_Slowpoke_Well_Map.png",
    LocationId::SLOWPOKE_WELL_B2F => "https://archives.bulbagarden.net/media/upload/5/5d/Johto_Slowpoke_Well_Map.png",
    LocationId::ILEX_FOREST => "https://archives.bulbagarden.net/media/upload/a/ae/Johto_Ilex_Forest_Map.png",
    LocationId::ROUTE_34 => "https://archives.bulbagarden.net/media/upload/7/70/Johto_Route_34_Map.png",
    LocationId::GOLDENROD_CITY => "https://archives.bulbagarden.net/media/upload/e/ec/Johto_Goldenrod_City_Map.png",
    LocationId::GOLDENROD_TUNNEL_B1F => "https://archives.bulbagarden.net/media/upload/e/ec/Johto_Goldenrod_City_Map.png",
    LocationId::GOLDENROD_TUNNEL_B2F => "https://archives.bulbagarden.net/media/upload/e/ec/Johto_Goldenrod_City_Map.png",
    LocationId::GOLDENROD_TUNNEL_WAREHOUSE => "https://archives.bulbagarden.net/media/upload/e/ec/Johto_Goldenrod_City_Map.png",
    LocationId::GOLDENROD_RADIO_TOWER_1F => "https://archives.bulbagarden.net/media/upload/e/ec/Johto_Goldenrod_City_Map.png",
    LocationId::GOLDENROD_RADIO_TOWER_2F => "https://archives.bulbagarden.net/media/upload/e/ec/Johto_Goldenrod_City_Map.png",
    LocationId::GOLDENROD_RADIO_TOWER_3F => "https://archives.bulbagarden.net/media/upload/e/ec/Johto_Goldenrod_City_Map.png",
    LocationId::GOLDENROD_RADIO_TOWER_4F => "https://archives.bulbagarden.net/media/upload/e/ec/Johto_Goldenrod_City_Map.png",
    LocationId::GOLDENROD_RADIO_TOWER_5F => "https://archives.bulbagarden.net/media/upload/e/ec/Johto_Goldenrod_City_Map.png",
    LocationId::GOLDENROD_RADIO_TOWER_OBSERVATION_DECK => "https://archives.bulbagarden.net/media/upload/e/ec/Johto_Goldenrod_City_Map.png",
    LocationId::GOLDENROD_MAGNET_TRAIN_STATION => "https://archives.bulbagarden.net/media/upload/e/ec/Johto_Goldenrod_City_Map.png",
    LocationId::MAGNET_TRAIN => "https://archives.bulbagarden.net/media/upload/4/49/Magnet_Train_GSC.png",
    LocationId::GOLDENROD_GYM => "https://archives.bulbagarden.net/media/upload/e/ec/Johto_Goldenrod_City_Map.png",
    LocationId::ROUTE_35 => "https://archives.bulbagarden.net/media/upload/9/96/Johto_Route_35_Map.png",
    LocationId::NATIONAL_PARK => "https://archives.bulbagarden.net/media/upload/4/4e/Johto_National_Park_Map.png",
    LocationId::ROUTE_36 => "https://archives.bulbagarden.net/media/upload/b/ba/Johto_Route_36_Map.png",
    LocationId::ROUTE_37 => "https://archives.bulbagarden.net/media/upload/d/dc/Johto_Route_37_Map.png",

    LocationId::SS_AQUA_1F => "https://archives.bulbagarden.net/media/upload/8/82/SS_Anne_FRLG.png",
    LocationId::SS_AQUA_B1F => "https://archives.bulbagarden.net/media/upload/8/82/SS_Anne_FRLG.png",
];
